# Generated by Django 5.0.7 on 2025-09-07 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unaerpcredentials',
            name='password',
        ),
        migrations.AddField(
            model_name='unaerpcredentials',
            name='encrypted_password',
            field=models.TextField(default='', verbose_name='Senha Criptografada'),
        ),
        migrations.AddField(
            model_name='unaerpcredentials',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
        migrations.AlterField(
            model_name='unaerpcredentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unaerp_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
